### ISSUE TITLE
No error when route is wrong 

### ISSUE THREAD

**Issue by akinyeleolubodun** [popphp/popphp#1]
This makes debugging and using this framework very difficult. It is fails gracefully and there is no how to know anything is wrong. It would be pleasant to include it.

**Comment by nicksagona** [comment]
Hey, thanks for the input. I had thought about adding default/no-match handling before, but my initial thinking was to leave it out so that a user could manually wire up their own no-match handlers. But, in the back of my mind I thought, that could be an issue. So, as suggested by your issue you've opened here, I've added default/no-match handling within the Match\Http and Match\Cli classes:

https://github.com/popphp/popphp/blob/master/src/Router/Match/Http.php#L290-L302

https://github.com/popphp/popphp/blob/master/src/Router/Match/Cli.php#L190-L203

The Http match object, outputs a 404 header with basic HTML saying "Page Not Found", and the CLI match object outputs a red-colored console "Command Not Found" message.

Of course, these defaults can still be overriden by defining your own error routes as well.

Check out the 2.0.0p1 release with this new patch in it.

**Comment by akinyeleolubodun** [comment]
In your implementation, you only wrote the method. You did not add it to the logic of the routes. I was thinking if someone tries using a route that can't be matched, then you call the method. This would have been lot easier. Then anybody can override what "noRouteFound " shows if need be. 

Would also like to know your thought on this.

It would be fine if this changes can be updated on the composer so I can upgrade the version of I have.

**Comment by akinyeleolubodun** [comment]
Thanks for your response. Will try that out now.

**Comment by nicksagona** [comment]
Actually, the logic is there in the `Pop\Application::run` method:

https://github.com/popphp/popphp/blob/master/src/Application.php#L515-L548

The new part is the call at the end of that block to noRouteFound() if a route isn't matched - that wasn't there before. So the flow is like this and you have two options:

##### Option 1 - No route found, use the `popphp` default handler:

``` php
$app = new Pop\Application(['routes' => [
    '/' => function() {
        echo 'Home Page';
    },
    '/hello/:name' => function($name) {
        echo 'Hello ' . $name;
    }
]]);
$app->run();
```

If you hit a route that's not defined in the above example, it'll automatically call the default response in `noRouteFound` method. So nothing extra or additional is needed from the user. If you want to override that, then you need to define a route to handle a non-match. One way to do that is to define a 'wildcard' route:

##### Option 2a - No route found, use 'wildcard' custom handler

``` php
$app = new Pop\Application(['routes' => [
    '/' => function() {
        echo 'Home Page';
    },
    '/hello/:name' => function($name) {
        echo 'Hello ' . $name;
    },
    '*' => function() {
        header('HTTP/1.1 404 Not Found');
        echo 'Page not found';
    }
]]);
$app->run();
```

In the above example, any non-matched route will get routed to that last 'Page Not Found' closure. Another way to do it is to define a controller as a 'default' handler, which can give you a little more control. This requires you to set up a 'default action' method in the controller class that serves as the fallback action if no route is found (usually that could be something like an `error` method):

##### Option 2b - No route found, use a default controller as a custom handler

``` php
$app = new Pop\Application(['routes' => [
    '/' => [
        'controller' => 'MyApp\Controller\IndexController'
        'action'     => 'index'
        'default'    => true
    ],
    '/hello/:name' => [
        'controller' => 'MyApp\Controller\IndexController'
        'action'     => 'hello'
    ]
]]);
$app->run();
```

The `'default' => true` config line marks that controller as the default controller to fallback on if there is no route match. In that controller class you would have a default action defined:

``` php
class MyApp\Controller\IndexController
{
    public function error()
    {
        header('HTTP/1.1 404 Not Found');
        echo 'Page not found';    
    }
}
```

Let me know if that helps. The changes were committed yesterday, so you should be able to update with composer and get the new `2.0.0p1` release (or download the changes in the ZIP file from the website.)

**Comment by akinyeleolubodun** [comment]
This is perfect. Thanks for your time.
