### ISSUE TITLE
PHP 8.1 - Serializable

### ISSUE THREAD

**Issue by marshmanGit** [popphp/popphp#10]
Hi Nick,
Will you consider making the required updates to address https://www.php.net/manual/en/migration81.deprecated.php

Looks like only a few files are involved
pop-csv/src/Csv.php
pop-db/src/Sql/Data.php
pop-utils/src/ArrayObject.php

Thank you for the great framework.
-marshall

**Comment by nicksagona** [comment]
Yes - getting the framework compatible with PHP v8 is on the roadmap to be done, hopefully soon. I'll keep you posted on the progress. Thanks for your intereset.

**Comment by nicksagona** [comment]
Ok - I've finished going through the entire framework to add support for PHP 8.1. Please pull down the latest version of the framework or this repo. The issues should be patched. Thanks for your continued support of Pop PHP.
