### ISSUE TITLE
Can the routes be dynamic

### ISSUE THREAD

**Issue by akinyeleolubodun** [popphp/popphp#2]
Can we have the routes not tied to specific controllers and actions. A route as below is tightly tied, not flexible.
            '/:controller/:action/:param' => [
                'controller' => 'IndexController',
                'action'     => 'index',
                'default'    => true
        ]

Can it be in the form below

```
        '/:controller/:action/:param' => [
            'namespace' => 'WhatEver',
            'controller' => 1,
            'action'     => 2,
            'default'    => true
    ]
```

Where 1 picks the controller, 2 picks the action or however. This would make the route dynamic.

**Comment by nicksagona** [comment]
It's interesting that you brought this up, as there was a version of dynamic routing in the legacy v1.\* branch of Pop. I didn't fully like the way it worked originally so I had stripped it out and thought about either re-working it or not including it in the v2.\* branch. (I ended up not including it, obviously.)

So, I revisited it and tried to keep it simple, including it in a new release. Take a look at the 2.0.1 release I just pushed up and see if it works for you. I wrote the outline of how to use it in the README.md file for now:

https://github.com/popphp/popphp#dynamic-routing

It's pretty similar to the example you used (which I believe is ZF1-ish and Phalcon-ish?)

Thanks

**Comment by akinyeleolubodun** [comment]
Nick, this is quite a good improvement. It works just perfect. What is wrong with your email dev@nolainteractive.com? I have sent couple of emails without any response. Yes, it is Phalcon-ish. Your framework structure is more like phalcon's too. I love the sleekless.

**Comment by nicksagona** [comment]
Great - glad to hear you like the addition. Ah - the email works, I just haven't checked it in a while (it's not my main email.) I'll go check it now. Thanks!
