### ISSUE TITLE
loadConfig missing?

### ISSUE THREAD

**Issue by ghost** [popphp/popphp#4]
I was looking at the documentation and I was interested in understanding what the loadConfig method does, but while I was looking for it in the whole framework I could not find it.

Where is this method defined?

The documentation page to which I refer is this: http://docs.popphp.org/en/latest/reference/pop_application.html

And the method is mentioned at the bottom of the API

**Comment by nicksagona** [comment]
Sorry about that - the docs weren't properly updated. Those methods have been replaced with the "register" methods:
- `registerConfig()`
- `registerRouter()`
- `registerServices()`
- `registerEvents()`
- `registerModules()`

I'll have to update the docs.

**Comment by ghost** [comment]
Perfect. 

Thanks

**Comment by nicksagona** [comment]
Ok the docs have been updated to reflect the correct methods.
