### ISSUE TITLE
Routes doesn't support except English characters

### ISSUE THREAD

**Issue by yusufusta** [popphp/popphp#6]
I don't know why isn't support.
I created a skeleton app with Kettle.

My config:
```
return [
    'routes' => [
        'get' => [
            '/' => [
                'controller' => 'api\Http\Controller\IndexController',
                'action'     => 'error'
            ],
        ],
        'get' => [
            '/hello/:name' => [
                'controller' => 'api\Http\Controller\IndexController',
                'action'     => 'hello'
            ],
        ],
    ],
    'database' => include __DIR__ . '/database.php',
    'http_options_headers' => [
        'Access-Control-Allow-Origin'  => '*',
        'Access-Control-Allow-Headers' => 'Accept, Authorization, Content-Type, X-Resource, X-Permission',
        'Access-Control-Allow-Methods' => 'HEAD, OPTIONS, GET, PUT, POST, PATCH, DELETE',
        'Content-Type'                 => 'application/json'
    ]
];
```

And my hello function:
```
    public function hello($name)
    {
        $this->send(200, ['Hello' => $name]);
    }
```

Results with screen-shots:
<img width="390" alt="Screen Shot 2020-06-14 at 17 13 16" src="https://user-images.githubusercontent.com/46392667/84595762-643d7a00-ae62-11ea-8dee-33aa6d674f0d.png">
<img width="373" alt="Screen Shot 2020-06-14 at 17 13 22" src="https://user-images.githubusercontent.com/46392667/84595766-669fd400-ae62-11ea-883e-db4f4ce31f18.png">

My system:
`PHP 7.2.30 MacOS Mojave`

Thanks!

**Comment by yusufusta** [comment]
Also, I tested with `?!,`. Result is same.

**Comment by nicksagona** [comment]
Hey - sorry just now getting some time to look at this issue. Please check out the latest version of this repo (3.5.0) as I've added unicode support for both HTTP and CLI routes. Let me know if this addresses the issue for you. Thanks.

**Comment by nicksagona** [comment]
Sorry - check out 3.5.1 - added unicode support in the values in the named parameters as well. Let me know if that addresses everything. Thanks.

**Comment by nicksagona** [comment]
Closing this issue out as completed.
